version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: