version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    networks:
      - brand-builder-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - brand-builder-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - brand-builder-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - brand-builder-network

volumes:
  mongodb_data:

networks:
  brand-builder-network:
    driver: bridge
