import { Link } from "@remix-run/react";

export default function Gdpr() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">
        Terms &amp; Conditions
      </h1>
      <p>Updated at 2023-11-17</p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        General Terms
      </h2>
      <p>
        By accessing <strong>Brand Builder</strong>, you confirm that you are in agreement
        with and bound by the terms of service contained in the Terms &amp;
        Conditions outlined below. These terms apply to the entire app and any
        email or other type of communication between you and <strong>Brand Builder</strong>.</p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        License
      </h2>
      <p>
        MPR Agency grants you a revocable, non-exclusive, non- transferable,
        limited license to download, install and use our service strictly in
        accordance with the terms of this Agreement.
      </p>
      
      <p>
        These Terms &amp; Conditions are a contract between you and MPR Agency
        (referred to in these Terms &amp; Conditions as &rdquo;MPR Agency&quot;,
        &rdquo;us&quot;, &quot;we&quot; or &quot;our&quot;), the provider of the
        MPR Agency website and the services accessible from the MPR Agency
        website (which are collectively referred to in these Terms &amp; Conditions as the
        &rdquo;MPR Agency Service&quot;).
      </p>
      
      <p>
        You are agreeing to be bound by these Terms &amp; Conditions. If you do
        not agree to these Terms &amp; Conditions, please do not use the
        Service. In these Terms &amp; Conditions, &quot;you&quot; refers both to
        you as an individual and to the entity you represent.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Definitions and key terms
      </h2>
      <p>For this Terms &amp; Conditions:</p>
      
      <p>
        &bull; Cookie: small amount of data generated by a website and saved by
        your web browser. lt is used to identify your browser, provide
        analytics, and remember information about you such as your language
        preference or login information.
      </p>
      <p>
        &bull; Company: when this policy mentions &rdquo;Company,&quot;
        &quot;we,&quot; &quot;us,&rdquo; or &rdquo;our,&rdquo; it refers to S.C.
        Medical PR Agency S.R.L., Bucuresti, Soseaua Ghe. I Sisesti, Nr. 225C,
        scara 1, parter, apartament 102, Sector 1 that is responsible for your
        information under this Privacy Policy.
      </p>
      <p>
        &bull; Country: where MPR Agency or the owners/founders of MPR Agency
        are based, in this case is Romania.
      </p>
      <p>
        &bull; Customer: refers to the company, organization or person that
        signs up to use the MPR Agency Service to manage the relationships with
        your consumers or service users.
      </p>
      <p>
        &bull; Device: any internet connected device such as a phone, tablet,
        computer or any other device that can be used to visit MPR Agency and
        use the services.
      </p>
      <p>
        &bull; IP address: Every device connected to the Internet is assigned a
        number known as an Internet protocol (IP) address. These numbers are
        usually assigned in geographic blocks. An IP address can often be used
        to identify the location from which a device is connecting to the
        Internet.
      </p>
      <p>
        &bull; Personnel: refers to those individuals Who are employed by MPR
        Agency or are under contract to perform a service on behalf of one of
        the parties.
      </p>
      <p>
        &bull; Personal Data: any information that directly, indirectly, or in
        connection with other information &mdash; including a personal
        identification number &mdash; allows for the identification or
        identifiability of a natural person.
      </p>
      <p>
        &bull; Service: refers to the service provided by MPR Agency as
        described in the relative terms (if available) and on this platform.
      </p>
      <p>
        &bull; Third-party service: refers to advertisers, contest sponsors,
        promotional and marketing partners, and others Who provide our content
        or whose products or services we think may interest you.
      </p>
      <p>
        &bull; Website: MPR Agency&apos;s site, which can be accessed via this
        URL: https://mpragency.ro/.
      </p>
      <p>
        &bull; You: a person or entity that is registered with MPR Agency to use
        the Services.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Restrictions
      </h2>
      <p>You agree not to, and you will not permit others to:</p>
      <p>
        &bull; License, sell, rent, lease, assign, distribute, transmit, host,
        outsource, disclose or otherwise commercially exploit the service or
        make the platform available to any third party.
      </p>
      <p>
        &bull; Modify, make derivative works of, disassemble, decrypt, reverse
        compile or reverse engineer any part of the service.
      </p>
      <p>
        &bull; Remove, alter or obscure any proprietary notice (including any
        notice of copyright or trademark) of MPR Agency or its affiliates,
        partners, suppliers or the licensors of the service.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Your Suggestions
      </h2>
      <p>
        Any feedback, comments, ideas, improvements or suggestions
        (collectively, &rdquo;Suggestions&quot;) provided by you to us with
        respect to the service shall remain the sole and exclusive property of
        us. We shall be free to use, copy, modify, publish, or redistribute the
        Suggestions for any purpose and in any way without any credit or any
        compensation to you.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Your Consent
      </h2>
      <p>
        We&apos;ve updated our Terms &amp; Conditions to provide you with
        complete transparency into what is being set when you visit our site and
        how iťs being used. By using our service, registering an account, or
        making a purchase, you hereby consent to our Terms &amp; Conditions.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Links to Other Websites
      </h2>
      <p>
        Our service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Terms
        &amp; Conditions of every site You visit. We have no control over and
        assume no responsibility for the content, Terms &amp; Conditions or
        practices of any third party sites or services.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Cookies
      </h2>
      <p>
        We use &rdquo;Cookies&rdquo; to identify the areas of our website that
        you have visited. A Cookie is a small piece of data stored on your
        computer or mobile device by your web browser. We use Cookies to enhance
        the performance and functionality of our service but are non-essential
        to their use. However, without these cookies, certain functionality like
        videos may become unavailable or you would be required to enter your
        login details every time you visit our platform as we would not be able
        to remember that you had logged in previously. Most web browsers can be
        set to disable the use of Cookies. However, if you disable Cookies, you
        may not be able to access functionality on our website correctly or at
        all. We never place Personally Identifiable Information in Cookies.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Changes To Our Terms &amp; Conditions
      </h2>
      <p>
        You acknowledge and agree that we may stop (permanently or temporarily)
        providing the Service (or any features within the Service) to you or to
        users generally at our sole discretion, without prior notice to you. You
        may stop using the Service at any time. You do not need to specifically
        inform us when you stop using the Service. You acknowledge and agree
        that if we disable access to your account, you may be prevented from
        accessing the Service, your account details or any files or Other
        materials which are contained in your account. If we decide to change
        our Terms &amp; Conditions, we will post those changes on this page,
        and/or update the Terms &amp; Conditions modification date below.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Modifications to Our service
      </h2>
      <p>
        We reserve the right to modify, suspend or discontinue, temporarily or
        permanently, the service or any service to which it connects, with or
        without notice and without liability to you.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Updates to Our service
      </h2>
      <p>
        We may from time to time provide enhancements or improvements to the
        features/ functionality of the service, which may include patches, bug
        fixes, updates, upgrades and Other modifications
        (&rdquo;Updates&rdquo;). Updates may modify or delete certain features
        and/or functionalities of the service. You agree that we have no obligation to
        (i) provide any Updates, or (ii) continue to provide or enable any
        particular features and/or functionalities of the service to you. You
        further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and
        conditions of this Agreement.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Third-Party Services
      </h2>
      <p>
        We may display, include or make available third-party content (including
        data, information, applications and Other products services) or provide
        links to third-party websites or services (&rdquo;Third- Party
        Services&quot;). You acknowledge and agree that we shall not be
        responsible for any Third-Party Services, including their accuracy,
        completeness, timeliness, validity, copyright compliance, legality,
        decency, quality or any Other aspect thereof. We do not assume and shall
        not have any liability or responsibility to you or any other person or
        entity for any Third-Party Services. Third-Party Services and links
        thereto are provided solely as a convenience to you and you access and
        use them entirely at your own risk and subject to such third
        parties&apos; terms and conditions.
      </p>
      
      <p>
        Your Personal Information may be shared with Third-Party Services only
        with your consent. Some Third-Party Services may store personal
        information outside the EU. In such cases, the Third-Party service
        providers are responsible with the security of your personal
        information, according to the GDPR regulations.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Term and Termination
      </h2>
      <p>
        This Agreement shall remain in effect until terminated by you or us. We
        may, in its sole discretion, at any time and for any or no reason,
        suspend or terminate this Agreement with or without prior notice. This
        Agreement will terminate immediately, without prior notice from us, in
        the event that you fail to comply with any provision of this Agreement.
        You may also terminate this Agreement by deleting the service and all
        copies thereof from your computer.
      </p>
      
      <p>
        Upon termination of this Agreement, you shall cease all use of the
        service and delete all copies of the service from your computer.
        Termination of this Agreement will not limit any of our rights or
        remedies at law or in equity in case of breach by you (during the term
        of this Agreement) of any of your obligations under the present
        Agreement.
      </p>
      
      <p>
        If you are a copyright owner or such owner&apos;s agent and believe any
        material from us constitutes an infringement on your copyright, please
        contact us setting forth the following information: (a) a physical or
        electronic signature of the copyright owner or a person authorized to
        act on his behalf; (b) identification of the material that is claimed to
        be infringing; (c) your contact information, including your address,
        telephone number, and an email; (d) a statement by you that you have a
        good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the
        information in the notification is accurate, and, under penalty of
        perjury you are authorized to act on behalf of the owner.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Indemnification
      </h2>
      <p>
        You agree to indemnify and hold us and our parents, subsidiaries,
        affiliates, officers, employees, agents, partners and licensors (if any)
        harmless from any claim or demand, including reasonable attorneys&apos;
        fees, due to or arising out of your: (a) use of the service; (b) violation of this Agreement or any law or regulation; or (c) violation
        of any right of a third party.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Limitation of Liability
      </h2>
      <p>
        Notwithstanding any damages that you might incur, the entire liability
        of us and any of our suppliers under any provision of this Agreement and
        your exclusive remedy for all of the foregoing shall be limited to the
        amount actually paid by you for the service. To the maximum extent
        permitted by applicable law, in no event shall we or our suppliers be
        liable for any special, incidental, indirect, or consequential damages
        whatsoever (including, but not limited to, damages for loss of profits,
        for loss of data or other information, for business interruption, for
        personal injury, for loss of privacy arising out of or in any way
        related to the use of or inability to use the service, third-party
        software and/or third-party hardware used with the service, or otherwise
        in connection with any provision of this Agreement), even if we or any
        supplier has been advised of the possibility of such damages and even if
        the remedy fails of its essential purpose. Some states/jurisdictions do
        not allow the exclusion or limitation of incidental or consequential
        damages, so the above limitation or exclusion may not apply to you.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Severability
      </h2>
      <p>
        If any provision of this Agreement is held to be unenforceable or
        invalid, such provision will be changed and interpreted to accomplish
        the objectives of such provision to the greatest extent possible under
        applicable law and the remaining provisions will continue in full
        force and effect. This Agreement, together with the Privacy Policy and
        any other legal notices published by us on the Services, shall
        constitute the entire agreement between you and us concerning the
        Services. If any provision of this Agreement is deemed invalid by a
        court of competent jurisdiction, the invalidity of such provision shall
        not affect the validity of the remaining provisions of this Agreement,
        which shall remain in full force and effect. No waiver of any term of
        this Agreement shall be deemed a further or continuing waiver of such 
        term or any other term, and our failure to assert any right or provision
        under this Agreement shall not constitute a waiver of such right or
        provision. YOU AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR
        RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES.
        OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Waiver
      </h2>
      <p>
        Except as provided herein, the failure to exercise a right or to require
        performance of an obligation under this Agreement shall not effect a
        party&apos;s ability to exercise such right or require such performance
        at any time thereafter nor shall be the waiver of a breach 
        constitute waiver of any subsequent breach. No failure to exercise, and
        no delay in exercising, on the part of either party, any right or any
        power under this Agreement shall 
        operate as a waiver of that right or power. Nor shall any single or
        partial exercise of any right or power under this Agreement preclude
        further exercise of that or any Other right granted herein. In the event
        of a conflict between this Agreement and any applicable purchase or Other terms, the terms of this Agreement shall govern.</p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Disclaimer
      </h2>
      <p>
        We are not responsible for any content, code or any Other imprecision.
        We do not provide warranties or guarantees. In no event shall we be
        liable for any special, direct, indirect, consequential, or incidental
        damages or any damages whatsoever, whether in an action 
        of contract, negligence or Other tort, arising out of or in connection
        with the use of the Service or the contents of the Service. We reserve
        the right to make additions, deletions, or modifications to the contents
        on the Service at any time without prior notice.
      </p>
      
      <p>
        Our Service and its contents are provided &rdquo;as is&quot; and
        &rdquo;as available&rdquo; without any warranty or representations of
        any kind, whether express or implied. We are a distributor and not a
        publisher of the content supplied by third parties; as such, our
        exercises no
        editorial control over such content and makes no warranty or
        representation as to the accuracy, reliability or currency of any
        information, content, service or merchandise provided through or
        accessible via our Service. Without limiting the foregoing, We
        specifically disclaim all warranties and representations in any content
        transmitted on or in connection with our Service or on sites that may
        appear as links on our Service, or in the products provided as a part
        of, or otherwise in connection with, our Service, including without
        limitation any warranties of merchantability, fitness for a particular
        purpose or non-infringement of third party rights. No oral advice or
        written information given by us or any of its afflliates, employees,
        officers, directors, agents, or the like will create a warranty. Price
        and availability information is subject to change without notice.
        Without limiting the foregoing, we do not warrant that our Service will
        be uninterrupted, uncorrupted, timely, or error-free.
      </p>
      
      <h2 className="text-xl font-bold mt-6 mb-2">
        Contact Us
      </h2>
      <p>Don&apos;t hesitate to contact us if you have any questions.</p>
      <p>&bull; Via Email: hello@mpragency.ro</p>
      <p>&bull; Via Phone Number: +40 723 333 793</p>

      <div className="flex items-center justify-start gap-x-6 mt-6 mb-6">
        <Link to="/" className="block w-full rounded-md px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 bg-indigo-600 hover:bg-indigo-500 focus-visible:outline-indigo-600">Inapoi</Link>
      </div>
    </div>
  );
}
